### ISSUE TITLE
Edit on root issue not displayed

### ISSUE THREAD

**Issue by NEA-SIS** [thomasrawiel/video-vtt#1]
Hi mr Rawiel,

in trying to make my page more accessible, i wanted to include captions on videos. I found your typo3 extension video vtt and installed it with no issue. (typo3 v.10.4.18)
Video control switches are working fine, but editing on root level does not show. It looks the same as without the video vtt extension. Video files are in mp4 format. 

What I tried so far:
- flushing the cache
- logging out and back in
- googling the issue (no success)
- deleting typo3/temp
- flushing the cache again
- checking all kinds of settings (e.g. template)

I'm at a loss. Do you have any clue why editig on oot level is not showing? 
I greatly appreaciate any help and I'm looking forward to hearing from you!
Thank you!

Kind regards
nea

**Comment by NEA-SIS** [comment]
Hi, no worries :)

However, no, that does not help. I do not have the tab "video" therefore can't upload a .vtt file. 
As I said, editing on root level (using your words) does not work because the option is not there. 
I read the doc more than a couple times..

Best regards.

**Comment by thomasrawiel** [comment]
I see...
That means you probably don't have the extension "Advanced file metadata" (Core-extension ext:filemetadata) installed, right?

I added that extension as a dependency.
Please try the latest version. (1.0.5). Download either from github or packagist if you use composer

**Comment by thomasrawiel** [comment]
If you still have issues, feel free to open a new ticket.
