### ISSUE TITLE
poster image

### ISSUE THREAD

**Issue by the-andyman** [thomasrawiel/video-vtt#2]
Thanks for the great extension!
is it possible to add an option/feature for a poster image?

**Comment by thomasrawiel** [comment]
This extensions intention is to just add the VTT and Mute/Autoplay etc. functions
A Poster Image feature would need to overwrite the FSC templates, that is currently not planned (or wanted) for this extension.

But feel free to fork :)

**Comment by thomasrawiel** [comment]
Completed with https://github.com/thomasrawiel/video-vtt/releases/tag/2.2.0
