### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by kimchristiansen** [thomasrawiel/video-vtt#4]
Is this extension still maintained? I would be very happy if the extension will be optimized for TYPO3 12.

**Comment by thomasrawiel** [comment]
Hi,
yes I plan on upgrading for v12. I don't know when I will have time, but feel free to fork and PR

**Comment by thomasrawiel** [comment]
I just pushed version [2.0.0](https://github.com/thomasrawiel/video-vtt/releases/tag/2.0.0) (only available via composer currently). 
Works for me with v12.4.2

Please test and report back any bugs you find, as I currently don't really have time to test this thoroughly.

Thanks!
